version: "3.8"

services:
  postgres:
    build: ./postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pesquisa
    ports:
      - "5432:5432"
    networks:
      - app-network

  mongodb:
    build: ./mongodb
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

  nodeapp:
    build: ./node-app
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge